config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  get 'home/index'

  resources :questions

  authenticated :user do
    root 'home#welcome'
  end
  unauthenticated :user do
    devise_scope :user do 
      root 'home#index', as: :unregistered_root
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  validates_length_of :description, minimum: 20
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable,:omniauthable, :omniauth_providers => [:facebook,:google_oauth2]
	after_create :build_username
	has_many :questions

    def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
			user.name = auth.info.name   # assuming the user model has a name
		end
	end
	def profile_picture
		if self.provider == "facebook"
			"http://graph.facebook.com/#{self.uid}/picture?width=140"
		elsif self.provider == "google_oauth2" and self.profile_picture_url
			self.profile_picture_url[0...-2] + "300"
		else
			"/default.jpg"
		end
	end
	
	def store_pp_google
		if self.provider == "google_oauth2"
			uri = URI.parse("https://www.googleapis.com/plus/v1/people/#{self.uid}?fields=image&key=#{ENV['google_api_key']}")
		    http = Net::HTTP.new(uri.host, uri.port)
			http.use_ssl = true
			http.verify_mode = OpenSSL::SSL::VERIFY_NONE
			request = Net::HTTP::Get.new(uri.request_uri)
		    response = http.request(request)
		    js = JSON.parse(response.body)
		    if js.has_key?("image")
		    	self.profile_picture_url = js["image"]["url"]
		    	self.save
		    end
		end
	end
	private
	def build_username
		self.username = Mail::Address.new(self.email).local
		self.save
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	#reset_session
  	render layout: "structure"
  end
  def welcome
  	@question = Question.new
  	
  	
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.limit(20).order("created_at DESC")
    
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title,:description)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		if @user.persisted?
			@user.remember_me = true
			sign_in_and_redirect @user, event: :authentication
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
      		#redirect_to new_user_registration_url
		end
	end
	def google_oauth2
		
		@user = User.from_omniauth(request.env["omniauth.auth"])
		if @user.persisted?
			@user.remember_me = true
			sign_in_and_redirect @user, event: :authentication
		else
			session["devise.google_data"] = request.env["omniauth.auth"]
      		redirect_to new_user_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_svg(path)
	    File.open("public/#{path}", "rb") do |file|
	    	raw file.read
	  	end
	end
	def render_profile_picture(user_pp,size=100)
		"<div style='width:#{size}px;height:#{size}px;background:url(#{user_pp});background-size:cover;border-radius:50%;background-position:center;'></div>"
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_aside.html.erb
<aside>
	
</aside>

app/views/home/_chat.html.erb
<div class="be-blue large-padding white">
	<div class="col-xs-10 inline-block">
		<i class="fa fa-user"></i> ¿Cómo funciona Tutoreandome?
	</div>
	<div class="col-xs-2 text-right inline-block">x</div>
</div>
<div class="large-padding be-light-facebook">
	<article class="top-space animated left soft-hidden">
		<div class="col-xs-3 col-md-2 inline-block no-padding">
			<%= image_tag('icons/student_pp.jpg') %>
		</div>
		<div class="col-md-8 inline-block " >
			<p class="large-padding white chat-message  ">
				¿Cómo puedo resolver esto?
			</p>
		</div>	
	</article>
	<article class="text-right top-space right animated soft-hidden delay-1">
		<div class="col-md-8 inline-block " >
			<p class="large-padding text-laft  white chat-message-blue ">
				Es fácil, sólo sigue estos pasos....
			</p>
		</div>	
	</article>
	<article class="top-space left animated soft-hidden delay-2">
		<div class="col-xs-3 col-md-2 inline-block no-padding">
			<%= image_tag('icons/student_pp.jpg') %>
		</div>
		<div class="col-md-8 inline-block " >
			<p class="large-padding white chat-message  ">
				¡Eres un genio! ¿Podemos agendar una asesoría?
			</p>
		</div>	
	</article>
	<article class="text-right top-space right animated soft-hidden delay-3">
		<div class="col-md-8 inline-block " >
			<p class="large-padding text-laft  white chat-message-blue ">
				Claro, en mi perfil aparecen los horarios en los que estoy disponible :)
			</p>
		</div>	
	</article>
	<article class="top-space left animated soft-hidden delay-4">
		<div class="col-xs-3 col-md-2 inline-block no-padding">
			<%= image_tag('icons/student_pp.jpg') %>
		</div>
		<div class="col-md-8 inline-block " >
			<p class="large-padding white chat-message  ">
				¿Qué te parece si agendamos 10 horas de 4-6pm?
			</p>
		</div>	
	</article>
	<article class="text-right top-space right animated soft-hidden delay-5">
		<div class="col-md-8 inline-block " >
			<p class="large-padding text-left  white chat-message-blue ">
				¡Me parece perfecto!
			</p>
		</div>	
	</article>
	<article class="top-space left animated soft-hidden delay-6">
		<div class="col-xs-3 col-md-2 inline-block no-padding">
			<%= image_tag('icons/student_pp.jpg') %>
		</div>
		<div class="col-md-8 inline-block " >
			<p class="large-padding white chat-message  ">
				Muchas gracias, acabas de salvar mi materia &lt;3
			</p>
		</div>	
	</article>
</div>
<script>
	var $chat = $('.animate-chat');
	$chat.find('.left').addClass('fadeInLeft');
	$chat.find('.right').addClass('fadeInRight');
</script>

app/views/home/index.html.erb
<header class="header_landing full-height center-vertical">

	<div class="large-padding col-md-8 no-float center-block white text-center">
        <%= image_tag("new-logo-light.png", class:"col-md-5 col-xs-8 col-sm-6 inline-block",style:"opacity:0.9;") %>
		<h1 class="text-shadow be-bigger">
			<strong>Tutoreando<span class="red">me</span></strong>		
		</h1>
		<p>¿Qué vas a aprender/enseñar hoy?</p>
		<div>
			<div class="col-sm-6 inline-block">
				<%= link_to user_omniauth_authorize_path(:google_oauth2), class: "btn btn-material-pink" do%>
					Ingresar con Google
				<%end%>
			</div>
			<div class="col-sm-6 inline-block">
				<%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-info", style:"background-color:#5264ae;" do%>
					Ingresar con Facebook
				<%end%>
			</div>
		</div>
	</div>	
	
</header>
<section class="full-height large-padding" style="width:100%;overflow-x:hidden;">
        <div class="col-md-11 full-height center-block no-float animate-chat text-center large-padding" ng-Controller="UnregisteredCtrl">
            <h2 class="bottom-space top-space">Todos <span class="red"><i class="mdi-action-favorite"></i></span> <%= image_tag("new-logo.png", class:"col-sm-2 col-xs-1 inline-block") %></h2>
            <div class="col-md-8 inline-block top-space">
                <nav class="medium-top-space text-left be-medium">
                    <ul class="no-list">
                        <li class="pointer box-shadow-right be-white large-padding inline-block col-md-3 col-xs-6" ng-click="setActive(0)"
                                ng-class="{'up-blue': active == 0}" style="margin-right:-5px;"> <i class="mdi-social-person"></i> Asesores </li>
                        <li class="pointer inline-block col-md-3 col-xs-6 be-white large-padding box-shadow-left" ng-click="setActive(1)"
                                ng-class="{'up-blue': active == 1}"> <i class="mdi-social-school"></i> Estudiantes </li>
                    </ul>
                </nav>
                <div class="top-space relative">
                    <div class="animated absolute" ng-class="active == 0 ? 'fadeInLeft': 'fadeOutRight'">
                        <div class="col-md-6 inline-block be-in-top top-space">
                            <%= image_tag("icons/school7.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Enseñas a distancia a alumnos de toda habla hispana.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top  top-space">
                            <%= image_tag("icons/first31.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Ganas medallas por apoyar a otros, y te damos prioridad cuando necesitas ayuda.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top  top-space">
                            <%= image_tag("icons/dollar179.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Obtienes comisiones por enseñar y ayudar a otros.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top top-space">

                            <%= image_tag("icons/grinning.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Recibe el reconocimiento de la gente a la que ayudas.
                            </p>
                        </div>
                    </div>
                    <div class="animated text-center absolute" ng-class="active == 1 ? 'fadeInLeft': 'fadeOutRight'">
                        <div class="col-md-6 inline-block be-in-top top-space">
                            <%= image_tag("icons/students2.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Resolución de tus dudas por expertos de todo el mundo.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top  top-space">
                            <%= image_tag("icons/trophy53.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Ganas medallas por apoyar a otros, y te damos prioridad cuando necesitas ayuda.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top  top-space">
                            <%= image_tag("icons/mobilephone17.png", class:"col-xs-3 inline-block") %>
                            <p class="top-space text-justify">
                                Asesorías personalizadas a bajo costo, desde tu móvil o computadora.
                            </p>
                        </div>
                        <div class="col-md-6 inline-block be-in-top top-space">
                            <%= image_tag("icons/online.png", class:"col-xs-4 inline-block") %>
                            <p class="top-space text-justify">
                                Acceso a vídeo llamadas, chat, notas, pizarrones y dudas con tu asesor.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1 inline-block"></div>
        	<div class="col-md-3 inline-block be-in-top text-left be-small border-box-shadow no-padding be-white box-shadow">
        		<%= render "home/chat" %>
        	</div>

        </div>
    </section>

app/views/home/welcome.html.erb
<div ng-controller="QuestionsCtrl">
	<div class="fixed" style="right:30px;bottom:30px;">
		
	</div>
	<div class="col-md-8 no-padding inline-block ">
		<header class="be-red white top-space">
			<nav class="large-padding" style="border-bottom:solid 1px #999;">
				<ul class="no-list white">
					<div class="col-xs-9 inline-block">
						<li class="inline-block col-sm-2 large-padding right-space be-white red">
							Dudas
						</li>
						<li class="inline-block large-padding">
							Asesorías disponibles
						</li>	
					</div>
					<li class="inline-block col-xs-3 pointer text-right large-padding open_question_form" ng-click="formVisible = !formVisible">
						<div class="col-xs-2 no-padding inline-block">
							<%= render_svg "svg-icons/question-navigation.svg" %>	
						</div>
						<div class="col-xs-9 inline-block no-padding text-left">
							Nueva pregunta	
						</div>
					</li>						
				</ul>
			</nav>
		</header>
		<section>
			<div class="large-padding top-space card slide"  ng-show="formVisible">
				<h2 class="be-medium blue">Nueva pregunta</h2>
				<%= render "questions/form" %>
			</div>
			<%= render "questions/question" %>
		</section>
	</div>
	<div class="col-md-4 inline-block">
		<%= render "home/aside" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutoreandome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
</head>
<body>
<div class="absolute snackbar toast snackbar-opened" style="z-index:1000;bottom:10px;left:10px;<%= "display:none;" if notice.nil? and alert.nil? %>"><span class="snackbar-content"><%= notice %><%= alert %></span></div>
	<%= render "partials/nav" %>
	<div id="user-data" class="absolute be-white box-shadow" data-open="false">
		<%= render "partials/user" %>	
	</div>
	<div class="col-md-11 col-sm-12 center-block no-float">
		<%= yield %>	
	</div>
	
	<script src="//cdnjs.cloudflare.com/ajax/libs/SVG-Morpheus/0.1.8/svg-morpheus.js"></script>
</body>
</html>

app/views/layouts/structure.html.erb
<!DOCTYPE html>
<html ng-app="mainModule">
<head>
  <title>Tutoreandome</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
</head>
<body>


<%= yield %>

</body>
</html>

app/views/partials/_nav.html.erb
<nav class="box-shadow relative" id="main-nav" style="z-index:100;">
	<ul class="large-padding be-blue white">
		<div class="col-xs-6 inline-block">
			<li class="inline-block be-regular right-space pointer" style="width:30px;" id="open_user_data"><%= render_svg "svg-icons/menu-navigation.svg" %></li>
			<li class="inline-block">
				<h1 class="no-margin be-medium">
				<%= link_to(root_path,class:"white") do%>
					<strong>Tutoreando<span class="black">me</span></strong>						
				<%end%>
				</h1>
			</li>	
		</div>
		<div class="col-xs-6 inline-block text-right">
			<li class="inline-block right-space"> <i class="mdi-communication-live-help"></i> Mis Dudas </li>
			<li class="inline-block"> <i class="mdi-communication-contacts"></i> Mis Asesorías </li>
		</div>		
	</ul>
</nav>

app/views/partials/_user.html.erb
<div>
	<header style="min-height:200px;" class="center-vertical header_user ">
		
		<div class="col-md-12 inline-block no-padding">
			<div class="circle-image no-margin" style="background:url(<%= current_user.profile_picture %>);background-size:cover;background-position:center;"></div>
			<div class="top-space white large-padding">
				<p><%= current_user.name %> - <strong class="blue"><%= current_user.username %></strong></p>
				<p><%= current_user.email %></p>			
			</div>
		</div>
	</header>
	<section>
		<nav class="large-padding">
			<ul class="no-list be-medium">
				<li class="top-space">
					<%= link_to(root_path, class:"btn btn-info btn-flat no-padding") do%>
						<i class="mdi-action-face-unlock dark-blue be-medium"></i> Mi perfil
					<%end%>
				</li>
				<li class="top-space">
					<%= link_to(root_path, class:"btn btn-info btn-flat no-padding") do%>
						<i class="mdi-action-account-circle dark-blue be-medium"></i> Configuraciones
					<%end%>
				</li>
				<li class="top-space">
					<%= link_to(destroy_user_session_path, :method => :delete, class:"btn btn-flat btn-danger no-padding") do%>
						<i class="mdi-action-settings dark-blue be-medium"></i> Cerrar sesión
					<%end%>
				</li>	
			</ul>
			
		</nav>
	</section>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question, html:  {:"ng-submit" => "addQuestion()"}) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :title, class:"form-control floating-label",placeholder:"Titulo", required:true,data:{hint:"Sé claro, el título permite que los asesores revisen tu duda"}, :"ng-model" => "newQuestion.title" %>
  </div>
  <div class="form-group">
    <div class="be-other-gray" id="editor" text-angular ng-model="newQuestion.description" class="border-bottom"  style="min-height:110px;" ta-toolbar="[['h1','h2','bold','pre','quote','ul','ol','insertImage']]" ta-toolbar-button-class="right-space like_link white inline-block" ta-toolbar-class="be-dark-blue large-padding" ta-toolbar-group-class="tool-t"></div>
    
  </div>
  <div class="actions form-group text-right">
    <%= f.submit "Guardar pregunta",class:"btn btn-flat no-padding btn-info right-space" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div ng-cloack class="transitionable"  ng-class="{'top-space': formVisible}">
	<article  class="large-padding be-white border-bottom transitionable animated fadeIn" ng-class="{'box-shadow tall-margin': question == activeQuestion}" ng-repeat="question in questions" ng-click="setActiveQuestion(question)">
		<div class="col-sm-1 col-xs-2 inline-block no-padding">
			<div back-img="{{question.user.profile_picture}}" style='width:60px;height:60px;border-radius:50%;'></div>
		</div>
		<div class="col-sm-11 col-xs-10 inline-block">
			<h3 class="dark-blue">{{ question.title }}</h3>
			<p class="gray transitionable overflow" ng-class="{'soft-hiden': activeQuestion != question}" ng-bind-html="question.description"></p>
			
		</div>
		
	</article>
</div>

app/views/questions/_toolbar.html.erb
<div id="wysihtml-toolbar" class="be-red large-padding">
	<a class="white right-space" data-wysihtml5-command="bold">Negritas</a>
	<a class="white right-space" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">Título</a>
	<a class="white right-space" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="p">Párrafo
	<a class="white right-space" data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="code">&lt;/&gt;</a>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>